Determine current branch.

diff --git a/bin/git b/bin/git
--- a/bin/git
+++ b/bin/git
@@ -60,12 +60,17 @@ git_nameit() {
 }
 
 git_pushit() {
-    local mainline remote
-    mainline="${GIT_PUSHIT_MAINLINE:-master}"
+    local current remote
     remote="${GIT_PUSHIT_REMOTE:-origin}"
 
+    current=$("$git" "${arg[@]}" symbolic-ref HEAD 2>/dev/null | cut -d/ -f3-)
+    if [ -z "$current" ]; then
+        echo "error: not on any branch." >&2
+        return 1
+    fi
+
     export GIT_NAMEIT_PREFIX="${GIT_PUSHIT_PREFIX:-$GIT_NAMEIT_PREFIX}"
-    "$git" "${arg[@]}" push "$remote" "$mainline":"$(git_nameit)"
+    "$git" "${arg[@]}" push "$remote" "$current":"$(git_nameit)"
 }
 
 git_set_url() {
